### ISSUE TITLE
是否支持企业微信的webhook机器人

### ISSUE THREAD

**Issue by feng-2019** [timonwong/prometheus-webhook-dingtalk#80]
目前在使用企业微信，也有群组机器人，webhook 格式，不知道是否可用

**Comment by feng-2019** [comment]
看了下和钉钉支持的格式差不多，text，markdown等

**Comment by timonwong** [comment]
首先我得说我很懒，而且已经不用钉钉了。。。
然后很多接入报警只支持钉钉的 webhook，所以我还做了个这个: https://github.com/timonwong/ding2wechat

需要注意的是 markdown 支持和消息体大小有所不同，不过可以一试

**Comment by feng-2019** [comment]
谢谢大佬

**Comment by feng-2019** [comment]
网上搜了很多，都没看到支持企业微信机器人的，谢谢大佬，

**Comment by feng-2019** [comment]
接收的url怎么填写，没看太明白wechat怎么弄

**Comment by timonwong** [comment]
你在 prometheus-webhook-dingtalk 的 url 里面，配置ding2wechat的 url 就可以了。
如果 ding2wechat 监听在 8080 端口，访问 `http://localhost:8080` 可以获得整个列表，如图所示:
![image](https://user-images.githubusercontent.com/1398228/71392534-55100900-2643-11ea-8999-9bacf544d659.png)

如果我们要发到「alerting」这个地方，在 prometheus-webhook-dingtalk 里面配置 `http://localhost:8080/receiver?name=alerting` 就可以了

**Comment by feng-2019** [comment]
大佬写一下微信的吧，这样的话就没那么麻烦了，辛苦，这样还需要转发，我使用最新的dingtalk测试了下，目前还没收到信息，我再测试下，看看哪里配错了

**Comment by feng-2019** [comment]
已经可以了，企业微信收到信息了，谢谢大佬指导。

**Comment by timonwong** [comment]
OK, 那我先把这个 issue 关掉了

**Comment by ownerlan** [comment]
你好，
config.yml配置的是
receivers:
  - name: webhook1
    targets:
      - url: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=xxxxxxxxxx

alertmanager.yml 配置的是：
- name: 'km_wechat3'
  webhook_configs:
  - url: 'http://127.0.0.1:8080/receiver?name=webhook1'
    send_resolved: true

然后alertmanager.yml 报400错误，需要怎么解决呢？
level=error ts=2020-11-23T02:39:16.529Z caller=dispatch.go:309 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="km_wechat3/webhook[0]: notify retry canceled due to unrecoverable error after 1 attempts: unexpected status code 400: http://127.0.0.1:8080/receiver?name=km_us_mysql_status1"

**Comment by ownerlan** [comment]
你好，
config.yml配置的是
receivers:

name: webhook1
targets:
url: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=xxxxxxxxxx
alertmanager.yml 配置的是：

name: 'km_wechat3'
webhook_configs:
url: 'http://127.0.0.1:8080/receiver?name=webhook1'
send_resolved: true
然后alertmanager.yml 报400错误，需要怎么解决呢？
level=error ts=2020-11-23T02:39:16.529Z caller=dispatch.go:309 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="km_wechat3/webhook[0]: notify retry canceled due to unrecoverable error after 1 attempts: unexpected status code 400: http://127.0.0.1:8080/receiver?name=webhook1"

**Comment by mxker** [comment]
> 

大佬，是使用的prometheus-webhook-dingtalk这个实现的吗？有什么指导不？
